### ISSUE TITLE
[feature request] Priviledge Verification

### ISSUE THREAD

**Issue by 299792458ms** [pythops/impala#13]
As of now impala requires to be run under elevated privilege with `sudo`.

Allowing users in the `wheel` or `netdev` group to run impala with no verification like one does with `iwctl` would be more convenient without sacrificing security completely.

Alternatively could be to request a secrets-manager/keyring to be unlocked and allow free access for as long as the manager is unlocked.

That is the gist of it.

**Comment by pythops** [comment]
Can you pull the last changes from main and try if it fixes the issue for you ? normally it should :sweat_smile:

**Comment by pythops** [comment]
Cool, I will close this one and release a new version.
Thanks again for reporting it
