### ISSUE TITLE
Confusing behavior when device is off

### ISSUE THREAD

**Issue by chrishoage** [pythops/impala#15]
I had a bit of a confusing experience just now: 

My thinkpad has a button to disable the wifi module, and it appears to do this at the hardware level. 

When running impala in this state there is just a blank application with no feedback whatsoever. 

I don't know what kind of visibility into the state of the device (I assume so, I was able to use iwctl to discover that the device was off), but if that state is available it would be nice to get some messaging around "no devices available" or something similar. 

Thank you for this wonderful project! It saves me from having to google how to use iwctl every time I connect to a new access point :sweat_smile:

**Comment by pythops** [comment]
Thanks, glad that you liked it.
Typical rfkill problem. I will fix it right away

**Comment by pythops** [comment]
fixed pushed to main. Let me know if it solves the issue :)

**Comment by pythops** [comment]
@chrishoage any updates ?

**Comment by chrishoage** [comment]
I honestly wasn't expecting such a fast turnaround time! 

I'm not anywhere close to my computer until later this evening Pacific Time. 

I will update this issue once I am able to give it a spin!

**Comment by pythops** [comment]
No worries, take your time :)

**Comment by chrishoage** [comment]
Looks like it works! tested with `cargo install --git https://github.com/pythops/impala.git` 

I also learned about rfkill - had no idea that existed, thank you! 


![Screenshot from 2024-09-10 17-21-13](https://github.com/user-attachments/assets/17b90a7b-9ca6-4e5c-9b5c-02eee5348f51)
