### ISSUE TITLE
Can't Start Impala

### ISSUE THREAD

**Issue by Tahinli** [pythops/impala#16]
Hi,

I couldn't start impala.
![image](https://github.com/user-attachments/assets/0a88f790-8065-4781-a1ea-1db794b8f409)

then I installed iwd and this time I got this:
![image](https://github.com/user-attachments/assets/8e1f4323-04f7-4e62-a459-e977cd3e37f3)

My System:

Fedora 40
Hyprland

**Comment by pythops** [comment]
Can you check if `iwd` is running ?
```
sudo systemctl status iwd
```
if not, make sure it is started and running them try again

**Comment by Tahinli** [comment]
Sorry I didn't know I need to start it.

I started iwd but this time I get nothing:

https://github.com/user-attachments/assets/6a577647-ac47-461b-8135-2c8f4349f8d8

**Comment by Tahinli** [comment]
tried with sudo, same result

**Comment by pythops** [comment]
if you look at the error message in iwd, you have your wifi device that is soft or hard blocked. If you have compiled from main you would see the message.
try this 
```
sudo rfkill unblock wlan
```
and then run impala with sudo

**Comment by Tahinli** [comment]
> if you look at the error message in iwd, you have your wifi device that is soft or hard blocked. If you have compiled from main you would see the message. try this
> 
> ```
> sudo rfkill unblock wlan
> ```
> 
> and then run impala with sudo

Thanks, it's running now.

If you can give some error prompt in program instead of unwrapping or giving empty GUI, it would be nice for users. Since not every person is capable of this kind of debugging. At least I completely forgot I disabled my wifi billion years ago. If you wouldn't be here, I was not going use impala and would say, hey it's broken.

It would be nice if you notify user about this circumstances.

**Comment by pythops** [comment]
Glad that it finally works. 
The last commit on the main branch is exactly for that, it's not released yet. but yeah a proper feedback for the users is important.
