### ISSUE TITLE
Black selection color when using black text color and light background

### ISSUE THREAD

**Issue by Kzinux** [pythops/impala#19]
Wezterm on archlinux, impala 0.2.3.
The selection color made the text unreadable.
![2024-11-09_17-51](https://github.com/user-attachments/assets/8ad8aaaf-a406-4d00-83b8-f745cd6c8a91)

**Comment by pythops** [comment]
@Kzinux 
can you try #20 PR

**Comment by Kzinux** [comment]
Thank you for your work.
My first time try to build rust code, the '#20 PR' fix the selection color.
Below is the newly build impala bin.
![2024-11-09_19-46](https://github.com/user-attachments/assets/a8572958-92d2-4922-9e8c-73cf9e9fe4c1)

**Comment by pythops** [comment]
Great ! 
I will merge it then and might do a release next week

**Comment by pythops** [comment]
@Kzinux I have just released a new version with your changes. enjoy :)
