### ISSUE TITLE
how to increase network name size?

### ISSUE THREAD

**Issue by Ahrirg** [pythops/impala#22]
give more option to increase characters for network name colum, cuz right now big wifi names are cut off

**Comment by pythops** [comment]
right now, the max size is 15 chars, do you think 30 chars would be enough ?

**Comment by pythops** [comment]
increased to 25 which should handle very large names

**Comment by Ahrirg** [comment]
it would be insanely nice if you added config option for name size + dividing new networks into 3 equal parts is not that efficient cuz signal + security would realistically would only use  +-20% of space, still thanks for help.
