### ISSUE TITLE
Packaging for Nix

### ISSUE THREAD

**Issue by Nydragon** [pythops/impala#3]
Hey, I'd be interested in packaging Impala for Nix and would like to know if that is OK.

**Comment by pythops** [comment]
Absolutely :100:  
Go for it :)

**Comment by Nydragon** [comment]
Related PR: https://github.com/NixOS/nixpkgs/pull/319553

**Comment by pythops** [comment]
Amazing, thanks :pray:

**Comment by Nydragon** [comment]
I activated notifications for releases on this repo so I am keeping an eye on it, but otherwise you would need to update the following 3 fields in the [package](https://github.com/NixOS/nixpkgs/pull/319553/files#diff-70da340fc5f05ea251fc7e8c414c8eae957aac2706429125f320846fe4058329) and submit a PR.

`  version = "0.1.1";`
`    hash = "sha256-r/aWzSn/Dci69oS/yopG6Ro34U8hniHVanctyM7RvDw=";`
`  cargoHash = "sha256-IV1ftsRyM0CUlQMVmLip1FiqnouT5TsKASpF/KLARqY=";`

The new hash & cargoHash are given to you when trying to build the package locally and if they are empty strings. So unless you already are using nix on your system, it would be quite the pain to do that

**Comment by pythops** [comment]
Excellent, thanks for the answer

**Comment by Nydragon** [comment]
Hey, got merged into master a couple of hours ago > https://nixpk.gs/pr-tracker.html?pr=319553

**Comment by pythops** [comment]
Thanks, I will mention it in the Readme then

**Comment by Nydragon** [comment]
Alright, thank you!

**Comment by Nydragon** [comment]
Oh and here is the link to the official package listings (its not updated yet): https://search.nixos.org/packages?show=impala

**Comment by pythops** [comment]
:thinking: here is what I can see 
![image](https://github.com/pythops/impala/assets/57548585/28b24afa-9577-4fbe-96a3-4543b969ff7f)

How should I write the instructions for nix installation ? Sorry but I never used Nix, I have no idea how it works :sweat_smile:

**Comment by Nydragon** [comment]
Hey, impala should pop up there in the following days when selecting the "unstable" version ([updated link](https://search.nixos.org/packages?channel=unstable&show=impala)), you can see the progress [here](https://nixpk.gs/pr-tracker.html?pr=319553), once nixos-unstable is checked, it should be visible in the first link. 

For install instructions I would write something like this:

> To install `impala`, either add it to your system configuration (recommended) or run:
>
> ```nix-env -iA nixos.impala```
>
> Or when flakes are enabled:
>
> ```nix profile install nixpkgs#impala``` 

But i think you could also just mention `nix-env -iA nixos.impala` and anyone using Nix can infer the other methods (I think)

**Comment by pythops** [comment]
Done
