### ISSUE TITLE
Homebrew

### ISSUE THREAD

**Issue by antonengelhardt** [pythops/impala#4]
It would be quite cool to install and update this via homebrew

**Comment by pythops** [comment]
Why not if some users might use it. 
Would you be okay to create the Fomula if create homebrew-impala repo ?

**Comment by antonengelhardt** [comment]
I haven't created formulas before, only casks, but I'll definitely try 👍🏻

**Comment by antonengelhardt** [comment]
Why do you want to create a repo though? Do you want to maintain your own tap?

**Comment by pythops** [comment]
No I don't want to maintain it :smile: 
Well in that case, if can let this issue open if someone wants to contribute to add homebrew :)

**Comment by pythops** [comment]
I'm closing this ticket as there is no update on it or any plan to fix it. might be reopened in the future if someone is willing to fix it
