### ISSUE TITLE
Need a DefaultStartMode config option

### ISSUE THREAD

**Issue by kimifish** [pythops/impala#5]
It would be great to have an opportunity to start program without choose-mode-box.

**Comment by pythops** [comment]
Good idea. 
How would you prefer it ? Do you wanna be able to set it from the cli, config file or have station for example as the default in the program logic ?

**Comment by kimifish** [comment]
The standard that I know is first look for a command line parameter, if not found environment var, then local config file then global config file. Although, the env variable in this case is clearly superfluous.

**Comment by pythops** [comment]
Done
