### ISSUE TITLE
Add Shift+Tab support for backwards switch

### ISSUE THREAD

**Issue by SergioShz** [pythops/impala#6]
Hi!! First of all, awesome project, I was looking for something like this and I love it ✨ 

It would be nice to be able to backwards switch between sections with some keybind combination (most natural case I think would be Shift+Tab since Tab is the main key to switch).

I think I could submit a PR (with my 0 knowledge of rust 😅 ) If you are interested on the feature, let me know what you think!!

**Comment by pythops** [comment]
Thanks :)
Sure, please do send a PR if you can, I think it's nice keybinding to have.

**Comment by pythops** [comment]
Done
