### ISSUE TITLE
Unreadable on light themed terminal

### ISSUE THREAD

**Issue by SevereOverfl0w** [pythops/impala#7]
The use of `white` for text means that the text is unreadable on a terminal with the theme in light mode.

**Comment by pythops** [comment]
Strange cause it supports already a white background.

Can you share here  a screenshot ?

**Comment by SevereOverfl0w** [comment]
![image](https://github.com/pythops/impala/assets/6136282/bbfa0455-ec6f-4cbf-9adf-26a7ae18bb80)

And here is the theme I am using with kitty

The problem is probably using "color white" rather than "foreground" and "background" for the text color.

```
background #ffffff
foreground #000000
selection_background #dfa0f0
selection_foreground #000000
url_color #193668
cursor #000000
cursor_text_color #ffffff

# Tabs
active_tab_background #ffffff
active_tab_foreground #193668
inactive_tab_background #c2c2c2
inactive_tab_foreground #000000
#tab_bar_background #dfdfdf

# Windows
active_border_color #3548cf
inactive_border_color #9f9f9f

# normal
color0 #ffffff
color1 #a60000
color2 #006800
color3 #6f5500
color4 #0031a9
color5 #721045
color6 #005e8b
color7 #000000

# bright
color8 #f2f2f2
color9 #d00000
color10 #008900
color11 #808000
color12 #0000ff
color13 #dd22dd
color14 #008899
color15 #595959

# extended colors
color16 #884900
color17 #7f0000
```

**Comment by pythops** [comment]
I have tried with `alacritty` with the default config which has a white background by default and it is working fine.
can you try with another terminal emulator like `alacritty` or `wezterm` for instance ?

**Comment by SevereOverfl0w** [comment]
This is likely down to this conversation: https://github.com/kovidgoyal/kitty/issues/541

**Comment by pythops** [comment]
I see. I will close this issue then as it is not related to any bug in `impala`

**Comment by pythops** [comment]
I do not need to agree with the kitty author when I have all those terminal emulators `alacritty` `wezterm` `xterm` work.
so I suggest that you either use another terminal emulator or use dark background or report the issue to `ratatui` which is the framework I am using to build this TUI.

**Comment by prepor** [comment]
the same issue with ghostty...

**Comment by Dai-JiaLin** [comment]
Same issue with wezterm-nightly using silk light (base16)
