### ISSUE TITLE
Some error happened when i try to use 's' in "Station" and AP error

### ISSUE THREAD

**Issue by peiwithhao** [pythops/impala#9]
![swappy-20240709-172242](https://github.com/pythops/impala/assets/97088532/05b92d4a-c675-4529-9028-966e992e2e09)
except that ,when i want to set the ap mode, how can i set the ap password, because when i input the ap ssid ,the "Access Point" just disappeared!
![image](https://github.com/pythops/impala/assets/97088532/0caaebbb-a600-4d3d-a026-7aa8383673b3)

**Comment by pythops** [comment]
fron the screenshots I can see, your device is on `stattion` mode. 
Try those steps:
1. `ctrl + r` to reset the mode and choose `access point`
2. Navigate to `access point` section and type `n` to create a new access point
3. Enter the name of your new ssid and password then type `enter`

![ap](https://github.com/pythops/impala/assets/57548585/7cffe947-8923-46bb-971f-3c2df465f6ee)

**Comment by peiwithhao** [comment]
> fron the screenshots I can see, your device is on `stattion` mode. Try those steps:
> 
> 1. `ctrl + r` to reset the mode and choose `access point`
> 2. Navigate to `access point` section and type `n` to create a new access point
> 3. Enter the name of your new ssid and password then type `enter`
> 
> ![ap](https://private-user-images.githubusercontent.com/57548585/346907173-7cffe947-8923-46bb-971f-3c2df465f6ee.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTg1NDAsIm5iZiI6MTcyMDUxODI0MCwicGF0aCI6Ii81NzU0ODU4NS8zNDY5MDcxNzMtN2NmZmU5NDctODkyMy00NmJiLTk3MWYtM2MyZGY0NjVmNmVlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA5NDQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNTZkZWI5NTEyODdlZDYxOWVlZWIzYmUzZmI3ZTdmYTRmMmRkOGE0ZTdlN2E5NTcwNjRjNDcxOTFjNmI3NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DLiC5LzZ_FELK-C8exv7OGWCA9mSo88Jcode1p_Jn9g) [ ![ap](https://private-user-images.githubusercontent.com/57548585/346907173-7cffe947-8923-46bb-971f-3c2df465f6ee.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTg1NDAsIm5iZiI6MTcyMDUxODI0MCwicGF0aCI6Ii81NzU0ODU4NS8zNDY5MDcxNzMtN2NmZmU5NDctODkyMy00NmJiLTk3MWYtM2MyZGY0NjVmNmVlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA5NDQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNTZkZWI5NTEyODdlZDYxOWVlZWIzYmUzZmI3ZTdmYTRmMmRkOGE0ZTdlN2E5NTcwNjRjNDcxOTFjNmI3NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DLiC5LzZ_FELK-C8exv7OGWCA9mSo88Jcode1p_Jn9g) ](https://private-user-images.githubusercontent.com/57548585/346907173-7cffe947-8923-46bb-971f-3c2df465f6ee.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTg1NDAsIm5iZiI6MTcyMDUxODI0MCwicGF0aCI6Ii81NzU0ODU4NS8zNDY5MDcxNzMtN2NmZmU5NDctODkyMy00NmJiLTk3MWYtM2MyZGY0NjVmNmVlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA5NDQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNTZkZWI5NTEyODdlZDYxOWVlZWIzYmUzZmI3ZTdmYTRmMmRkOGE0ZTdlN2E5NTcwNjRjNDcxOTFjNmI3NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DLiC5LzZ_FELK-C8exv7OGWCA9mSo88Jcode1p_Jn9g) [ ](https://private-user-images.githubusercontent.com/57548585/346907173-7cffe947-8923-46bb-971f-3c2df465f6ee.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTg1NDAsIm5iZiI6MTcyMDUxODI0MCwicGF0aCI6Ii81NzU0ODU4NS8zNDY5MDcxNzMtN2NmZmU5NDctODkyMy00NmJiLTk3MWYtM2MyZGY0NjVmNmVlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA5NDQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNTZkZWI5NTEyODdlZDYxOWVlZWIzYmUzZmI3ZTdmYTRmMmRkOGE0ZTdlN2E5NTcwNjRjNDcxOTFjNmI3NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DLiC5LzZ_FELK-C8exv7OGWCA9mSo88Jcode1p_Jn9g)

Thanks for the reply!But why does a red box error appear when trying to start scanning on the station?

**Comment by pythops** [comment]
:thinking: 
did you run `impala` with `sudo` or as `root` ?

**Comment by peiwithhao** [comment]
> 🤔 did you run `impala` with `sudo` or as `root` ?

also same error :(

**Comment by pythops** [comment]
try this then:
```
$ sudo iwctl
[iwd]# station wlan0 scan
```
Do you get any error ?

btw, can you share those information: 
- OS
- iwd version that you can get with this command: `sudo iwctl version` 
- errors or warnings in iwd that you can get with this command:  `sudo journalctl -f -u iwd`

**Comment by peiwithhao** [comment]
+ archlinux 6.9.8-arch1-1
![image](https://github.com/pythops/impala/assets/97088532/676ef985-c638-4b5f-9f65-750c59826b90)
just report the Operaation not supported, I think maybe it's just iw's problem

**Comment by pythops** [comment]
Yeah, this seems to be related to `iwd`.
You can check `rfkill` to see if the wifi has been blocked or not.
there also this reddit thread, you might find the solution for your problem there.

I will close this issue as it's not related directly to `impala`

**Comment by peiwithhao** [comment]
Thank you for your reply!

**Comment by pythops** [comment]
You are welcome. Feel free to open an issue if you face any issue with impala
